services:
  avto_salon:
    container_name: avto-salon-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    networks: 
      - monorepo-network

networks:
  monorepo-network:
    external: true
    name: brand_cars_monorepo-network

