FROM node:20.10.0

# Set working directory
WORKDIR /usr/src/avto-salon

# Copy everything
COPY . .

# Install dependencies
RUN npm install --legacy-peer-deps

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]

