import React from 'react';
import { Car } from '../../types/car/car';
import CarCard from './CarCard';
import { Grid, Typography, Box } from '@mui/material';
import { 
  CarTransactionType, 
  CarCategory, 
  CarStatus, 
  CarLocation, 
  CarBrand, 
  FuelType, 
  TransmissionType, 
  CarCondition 
} from '../../enums/car.enum';
import { MemberType, MemberStatus, MemberAuthType } from '../../enums/member.enum';

const MockCarData: React.FC = () => {
  // Mock car data to demonstrate the design
  const mockCars: Car[] = [
    {
      _id: '1',
      carTransactionType: CarTransactionType.BUY,
      carCategory: CarCategory.LUXURY,
      carStatus: CarStatus.AVAILABLE,
      carLocation: CarLocation.LOS_ANGELES,
      carAddress: 'Beverly Hills, CA',
      carTitle: '2023 Rolls-Royce Phantom',
      carPrice: 450000,
      carYear: 2023,
      carSeats: 5,
      carDoors: 4,
      carViews: 1250,
      carLikes: 89,
      carComments: 12,
      carRank: 95,
      carImages: ['img/cars/rolls-phantom.jpg'],
      carDesc: 'Ultimate luxury sedan with handcrafted interior',
      isBarterAvailable: false,
      isForRent: false,
      discountPercent: 0,
      discountedPrice: 450000,
      memberId: 'member1',
      brand: CarBrand.ROLLS_ROYCE,
      createdAt: new Date('2023-01-15T00:00:00Z'),
      updatedAt: new Date('2024-01-15T00:00:00Z'),
      memberData: {
        _id: 'member1',
        memberType: MemberType.AGENT,
        memberStatus: MemberStatus.ACTIVE,
        memberAuthType: MemberAuthType.EMAIL,
        memberPhone: '+1-555-0123',
        memberNick: 'LuxuryCarsLA',
        memberFullName: 'John Smith',
        memberImage: '/img/profile/agent.png',
        memberAddress: 'Los Angeles, CA',
        memberDesc: 'Premium luxury car specialist',
        memberCars: 15,
        memberArticles: 8,
        memberFollowers: 1200,
        memberFollowings: 150,
        memberPoints: 2500,
        memberLikes: 890,
        memberViews: 15000,
        memberComments: 45,
        memberRank: 95,
        memberBlocks: 0,
        memberWarnings: 0,
        deletedAt: undefined,
        createdAt: new Date('2023-01-15T00:00:00Z'),
        updatedAt: new Date('2024-01-15T00:00:00Z'),
        accessToken: '',
        meLiked: [],
        meFollowed: []
      }
    },
    {
      _id: '2',
      carTransactionType: CarTransactionType.BUY,
      carCategory: CarCategory.LUXURY,
      carStatus: CarStatus.AVAILABLE,
      carLocation: CarLocation.PARIS,
      carAddress: 'Champs-Élysées, Paris',
      carTitle: '2024 Bentley Continental GT',
      carPrice: 320000,
      carYear: 2024,
      carSeats: 4,
      carDoors: 2,
      carViews: 980,
      carLikes: 67,
      carComments: 8,
      carRank: 92,
      carImages: ['img/cars/bentley-continental.jpg'],
      carDesc: 'Elegant grand tourer with exceptional performance',
      isBarterAvailable: true,
      isForRent: false,
      discountPercent: 5,
      discountedPrice: 304000,
      memberId: 'member2',
      brand: CarBrand.BENTLEY,
      createdAt: new Date('2023-02-15T00:00:00Z'),
      updatedAt: new Date('2024-02-15T00:00:00Z'),
      memberData: {
        _id: 'member2',
        memberType: MemberType.AGENT,
        memberStatus: MemberStatus.ACTIVE,
        memberAuthType: MemberAuthType.EMAIL,
        memberPhone: '+33-1-555-0123',
        memberNick: 'ParisLuxury',
        memberFullName: 'Marie Dubois',
        memberImage: '/img/profile/agent.png',
        memberAddress: 'Paris, France',
        memberDesc: 'European luxury car expert',
        memberCars: 12,
        memberArticles: 6,
        memberFollowers: 850,
        memberFollowings: 120,
        memberPoints: 1800,
        memberLikes: 650,
        memberViews: 12000,
        memberComments: 32,
        memberRank: 88,
        memberBlocks: 0,
        memberWarnings: 0,
        deletedAt: undefined,
        createdAt: new Date('2023-02-20T00:00:00Z'),
        updatedAt: new Date('2024-01-15T00:00:00Z'),
        accessToken: '',
        meLiked: [],
        meFollowed: []
      }
    },
    {
      _id: '3',
      carTransactionType: CarTransactionType.BUY,
      carCategory: CarCategory.LUXURY,
      carStatus: CarStatus.AVAILABLE,
      carLocation: CarLocation.DUBAI,
      carAddress: 'Palm Jumeirah, Dubai',
      carTitle: '2024 Lamborghini Huracán',
      carPrice: 280000,
      carYear: 2024,
      carSeats: 2,
      carDoors: 2,
      carViews: 2100,
      carLikes: 145,
      carComments: 23,
      carRank: 98,
      carImages: ['img/cars/lambo-huracan.jpg'],
      carDesc: 'Exotic supercar with breathtaking performance',
      isBarterAvailable: false,
      isForRent: true,
      discountPercent: 0,
      discountedPrice: 280000,
      memberId: 'member3',
      brand: CarBrand.LAMBORGHINI,
      createdAt: new Date('2023-03-15T00:00:00Z'),
      updatedAt: new Date('2024-03-15T00:00:00Z'),
      memberData: {
        _id: 'member3',
        memberType: MemberType.AGENT,
        memberStatus: MemberStatus.ACTIVE,
        memberAuthType: MemberAuthType.EMAIL,
        memberPhone: '+971-4-555-0123',
        memberNick: 'DubaiExotics',
        memberFullName: 'Ahmed Al-Rashid',
        memberImage: '/img/profile/agent.png',
        memberAddress: 'Dubai, UAE',
        memberDesc: 'Exotic and supercar specialist',
        memberCars: 8,
        memberArticles: 4,
        memberFollowers: 2000,
        memberFollowings: 80,
        memberPoints: 3200,
        memberLikes: 1200,
        memberViews: 25000,
        memberComments: 67,
        memberRank: 98,
        memberBlocks: 0,
        memberWarnings: 0,
        deletedAt: undefined,
        createdAt: new Date('2023-03-10T00:00:00Z'),
        updatedAt: new Date('2024-01-15T00:00:00Z'),
        accessToken: '',
        meLiked: [],
        meFollowed: []
      }
    },
    {
      _id: '4',
      carTransactionType: CarTransactionType.BUY,
      carCategory: CarCategory.LUXURY,
      carStatus: CarStatus.AVAILABLE,
      carLocation: CarLocation.TOKYO,
      carAddress: 'Ginza District, Tokyo',
      carTitle: '2024 Lexus LS 500',
      carPrice: 95000,
      carYear: 2024,
      carSeats: 5,
      carDoors: 4,
      carViews: 750,
      carLikes: 45,
      carComments: 6,
      carRank: 85,
      carImages: ['img/cars/lexus-rx.jpg'],
      carDesc: 'Japanese luxury with cutting-edge technology',
      isBarterAvailable: true,
      isForRent: false,
      discountPercent: 8,
      discountedPrice: 87400,
      memberId: 'member4',
      brand: CarBrand.LEXUS,
      createdAt: new Date('2023-04-15T00:00:00Z'),
      updatedAt: new Date('2024-04-15T00:00:00Z'),
      memberData: {
        _id: 'member4',
        memberType: MemberType.AGENT,
        memberStatus: MemberStatus.ACTIVE,
        memberAuthType: MemberAuthType.EMAIL,
        memberPhone: '+81-3-555-0123',
        memberNick: 'TokyoLuxury',
        memberFullName: 'Yuki Tanaka',
        memberImage: '/img/profile/agent.png',
        memberAddress: 'Tokyo, Japan',
        memberDesc: 'Japanese luxury car specialist',
        memberCars: 18,
        memberArticles: 10,
        memberFollowers: 950,
        memberFollowings: 200,
        memberPoints: 2200,
        memberLikes: 780,
        memberViews: 18000,
        memberComments: 55,
        memberRank: 90,
        memberBlocks: 0,
        memberWarnings: 0,
        deletedAt: undefined,
        createdAt: new Date('2023-01-05T00:00:00Z'),
        updatedAt: new Date('2024-01-15T00:00:00Z'),
        accessToken: '',
        meLiked: [],
        meFollowed: []
      }
    },
    {
      _id: '5',
      carTransactionType: CarTransactionType.BUY,
      carCategory: CarCategory.LUXURY,
      carStatus: CarStatus.AVAILABLE,
      carLocation: CarLocation.NEW_YORK,
      carAddress: 'Manhattan, NYC',
      carTitle: '2024 Mercedes-Benz S-Class',
      carPrice: 180000,
      carYear: 2024,
      carSeats: 5,
      carDoors: 4,
      carViews: 890,
      carLikes: 58,
      carComments: 9,
      carRank: 87,
      carImages: ['/img/cars/mercedes-s.jpg'],
      carDesc: 'The benchmark for luxury sedans',
      isBarterAvailable: false,
      isForRent: true,
      discountPercent: 0,
      discountedPrice: 180000,
      memberId: 'member5',
      brand: CarBrand.MERCEDES,
      createdAt: new Date('2023-05-15T00:00:00Z'),
      updatedAt: new Date('2024-05-15T00:00:00Z'),
      memberData: {
        _id: 'member5',
        memberType: MemberType.AGENT,
        memberStatus: MemberStatus.ACTIVE,
        memberAuthType: MemberAuthType.EMAIL,
        memberPhone: '+1-212-555-0123',
        memberNick: 'NYCLuxury',
        memberFullName: 'Michael Johnson',
        memberImage: '/img/profile/agent.png',
        memberAddress: 'New York, NY',
        memberDesc: 'Manhattan luxury car dealer',
        memberCars: 22,
        memberArticles: 12,
        memberFollowers: 1500,
        memberFollowings: 180,
        memberPoints: 2800,
        memberLikes: 950,
        memberViews: 22000,
        memberComments: 78,
        memberRank: 92,
        memberBlocks: 0,
        memberWarnings: 0,
        deletedAt: undefined,
        createdAt: new Date('2023-02-15T00:00:00Z'),
        updatedAt: new Date('2024-01-15T00:00:00Z'),
        accessToken: '',
        meLiked: [],
        meFollowed: []
      }
    },
    {
      _id: '6',
      carTransactionType: CarTransactionType.BUY,
      carCategory: CarCategory.LUXURY,
      carStatus: CarStatus.AVAILABLE,
      carLocation: CarLocation.SEOUL,
      carAddress: 'Gangnam District, Seoul',
      carTitle: '2024 BMW X7 M60i',
      carPrice: 140000,
      carYear: 2024,
      carSeats: 7,
      carDoors: 5,
      carViews: 650,
      carLikes: 38,
      carComments: 5,
      carRank: 82,
      carImages: ['/img/cars/bmw-x7.jpg'],
      carDesc: 'Ultimate luxury SUV with M performance',
      isBarterAvailable: true,
      isForRent: false,
      discountPercent: 3,
      discountedPrice: 135800,
      memberId: 'member6',
      brand: CarBrand.BMW,
      createdAt: new Date('2023-06-15T00:00:00Z'),
      updatedAt: new Date('2024-06-15T00:00:00Z'),
      memberData: {
        _id: 'member6',
        memberType: MemberType.AGENT,
        memberStatus: MemberStatus.ACTIVE,
        memberAuthType: MemberAuthType.EMAIL,
        memberPhone: '+82-2-555-0123',
        memberNick: 'SeoulLuxury',
        memberFullName: 'Ji-hyun Kim',
        memberImage: '/img/profile/agent.png',
        memberAddress: 'Seoul, South Korea',
        memberDesc: 'Korean luxury car expert',
        memberCars: 14,
        memberArticles: 7,
        memberFollowers: 680,
        memberFollowings: 120,
        memberPoints: 1600,
        memberLikes: 520,
        memberViews: 11000,
        memberComments: 28,
        memberRank: 85,
        memberBlocks: 0,
        memberWarnings: 0,
        deletedAt: undefined,
        createdAt: new Date('2023-03-20T00:00:00Z'),
        updatedAt: new Date('2024-01-15T00:00:00Z'),
        accessToken: '',
        meLiked: [],
        meFollowed: []
      }
    }
  ];

  const likeCarHandler = async (user: any, id: string) => {
    console.log('Like car:', id);
  };

  return (
    <Box component="div"   sx={{ p: 2 }}>
      <Typography variant="h5" sx={{ mb: 2, color: '#D4AF37', fontWeight: 600 }}>
        🚗 Mock Car Data - Design Preview
      </Typography>
      <Typography variant="body2" sx={{ mb: 3, color: '#666' }}>
        This shows how the car listings will look when data is available from the database.
      </Typography>
      
      <Grid container spacing={3}>
        {mockCars.map((car, index) => (
          <Grid
            item
            xs={12}
            sm={6}
            md={4}
            lg={4}
            key={car._id}
          >
            <CarCard
              car={car}
              likeCarHandler={likeCarHandler}
            />
          </Grid>
        ))}
      </Grid>
    </Box>
  );
};

export default MockCarData;
